pipeline {
    agent any
    
    tools {
        maven 'Maven 3.9'
    }
    
    stages {
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                bat 'mvn clean package'
            }
        }
        stage('Complete') {
            steps {
                echo 'Pipeline completed successfully!'
            }
        }
    }
}
